name: My First Worklflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v6

        - name: List and readfile
          run: |
            echo "My first github page"
            ls -ltra
            cat README.md

        - name: Generate ASCII artwork
          run: cowsay -f dragon "Run for cover, I am dragon.....RAWR" >> dragon.txt